# Node Names
RETRIEVE = "retrieve"
GRADE_DOCUMENTS = "grade_documents"
GENERATE = "generate"
WEBSEARCH = "websearch"

# Model Names
DEFAULT_MODEL = "gpt-4o-mini-2024-07-18"
GENERATION_MODEL = DEFAULT_MODEL
HALLUCINATION_GRADER_MODEL = DEFAULT_MODEL
RETRIEVAL_GRADER_MODEL = DEFAULT_MODEL
ANSWER_GRADER_MODEL = DEFAULT_MODEL
